### PR TITLE
Run support/update.js

### PR DESCRIPTION
**Pull request by f0rr0**
Github emoji have been updated.

### CODE REVIEW

**Comment by puzrin** [comment]
Thanks for info.

Content of `light` version is wrong, i'll update package myself in the nearest time.

**Comment by f0rr0** [comment]
Yeah I just realized the CI test failed, I guess you should update `light` to Unicode 6.0

**Comment by puzrin** [comment]
No, that seems to be due lodash api change between 3->4. light version should not be changed at all.

**Comment by f0rr0** [comment]
Strange..I did not update any dependencies. I think you should consider specifying versions in your `package.json` or use `shrinkwrap`

**Comment by puzrin** [comment]
That's because all was done when lodash was 3.x, and now it's 4.x.

I'll fix it soon.

**Comment by puzrin** [comment]
I've commited fixed scripts, but don't like result. Light version was changed:

```diff
+  "pout": "😡",
-  "star": "⭐",
-  "zap": "⚡",
-  "umbrella": "☔",
-  "hourglass": "⌛",
-  "watch": "⌚",
-  "mahjong": "🀄",
-  "coffee": "☕",
-  "anchor": "⚓",
-  "wheelchair": "♿",
-  "aries": "♈",
-  "taurus": "♉",
-  "gemini": "♊",
-  "cancer": "♋",
-  "leo": "♌",
-  "virgo": "♍",
-  "libra": "♎",
-  "scorpius": "♏",
-  "sagittarius": "♐",
-  "capricorn": "♑",
-  "aquarius": "♒",
-  "pisces": "♓",
-  "exclamation": "❗",
-  "heavy_exclamation_mark": "❗",
-  "black_medium_small_square": "◾",
-  "white_medium_small_square": "◽",
-  "black_circle": "⚫",
-  "white_circle": "⚪",
-  "white_large_square": "⬜",
-  "black_large_square": "⬛"
```

Probably, guys from github changed glyph codes. Need to recheck content of https://github.com/markdown-it/markdown-it-emoji/blob/master/support/visible.txt

**Comment by f0rr0** [comment]
@puzrin Let me know if you need help, I'm currently using my own fork for my project.

**Comment by puzrin** [comment]
I've scheduled "light" chars list recheck to the start of nearest week, if not urgent. Need to manually check changed chars - are those available in some OS-es or not. Main criteria of light list - chars should exist on the most of devices.

**Comment by puzrin** [comment]
More fixes in master. Light data is now ok. But full data still has some garbage with names "uXXXX".

I think we will finish tomorrow.

**Comment by puzrin** [comment]
Closing - everything fixed in 1.3.0

**Pull request closed without merging**
